language: csharp
mono:
  - latest
  - 3.12.0
  - 3.10.0
solution: Source/NShape.sln
install:
  - nuget restore Source\ -PackagesDirectory Source\.nuget\packages\
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Debug Source/NShape.sln
